[simulation]
num_generations = 10
num_instances = 10
host_popsize = 10
epidemic_model = "sir"
coinfection = false
pathogen_path = "examples/test1.sir.pathogens.fa"
host_network_path = "examples/test1.sir.network.txt"

[logging]
log_freq = 1
log_path = "examples/test1.sir.log"

[[intrahost_model]]
model_name = "constant-high_mutation"
host_ids = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
mutation_rate = 0.01
transition_matrix = [
  [ 0.0e+00, 1.0e+00 ],
  [ 1.0e+00, 0.0e+00 ],
]
recombination_rate = 0.0
replication_model = "constant"
constant_pop_size = 100
infected_duration = 3

[[fitness_model]]
model_name = "multiplicative"
host_ids = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
fitness_model = "multiplicative"
fitness_model_path = "examples/test1.sir.fm.txt"

[[transmission_model]]
model_name = "multiplicative"
host_ids = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
mode = "constant"
transmission_prob = 1.0
transmission_size = 1.0
